version: 2.1

orbs:
  ruby: circleci/ruby@0.1.2

executors:
  ruby30:
    docker:
      - image: circleci/ruby:3.0-node-browsers
  ruby27:
    docker:
      - image: circleci/ruby:2.7-node-browsers

jobs:
  props-template:
    parameters:
      ruby-version:
        type: executor
      gemfile:
        type: string
    executor: << parameters.ruby-version >>
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
          name: Using Gemfile
          command: mv -f ./<< parameters.gemfile >> ./Gemfile
      - run:
          name: Bundle install
          command: bundle install
      - run:
          name: Rspec
          command: bundle exec rspec

workflows:
  tests:
    jobs:
      - props-template:
          matrix:
            parameters:
              gemfile:
                - Gemfile.rails60
                - Gemfile.rails61
                - Gemfile.rails70
              ruby-version:
                - ruby27
                - ruby30
